name: "Cleanup issues & PRs"

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  lock:
    name: 🔒 Lock issues & PRs closed over a year
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/lock-threads@v2
        with:
          github-token: ${{ github.token }}
          issue-lock-comment: ""
          pr-lock-comment: ""
