name: Close Pull Request

on:
  pull_request_target:
    types: [opened]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: superbrothers/close-pull-request@v3
        with:
          comment: |
            This repository is strictly for legacy support of OctoPrint versions before 1.8.0 and will only see updates
            in an absolute emergency.

            All current development happens at [OctoPrint/OctoPrint](https://github.com/OctoPrint/OctoPrint)
            and that is also where you should direct issues and PRs.
